baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
theme: "PaperMod"
module: 
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

enableEmoji: true

params:
  author: knight
  ShowPostNavLinks: true
  Email: 3508hack@gmail.com

menu:
  main:
   - name: Posts
     url: /posts/
     weight: 1
   - name: Notes
     url: /notes/
     weight: 2


