baseURL: http://knightsnape.github.io
languageCode: en-us
title: My New Hugo Site
theme: "PaperMod"
module: 
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

  fr:
    languageName: ":fr:"
    weight: 2
    title: PaperModL2
    taxonomies:
      category: FRcategories
      tag: FRtags
      series: FRseries
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 5
        - name: FRTags
          url: frtags
          weight: 10
        - name: FRCategories
          url: frcategories
          weight: 10
        - name: FRSeries
          url: frseries
          weight: 10
        - name: NullLink
          url: "#"

  fa:
    languagedirection: rtl
    weight: 3
    title: PaperMod RTL
    taxonomies:
      category: FAcategories
      tag: FAtags
      series: FAseries
    menu:
      main:
        - name: FATags
          url: fatags
          weight: 10
    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to RTL layout

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperMod - https://github.com/KnightSnape/knightsnape.github.io"
  author: Theme PaperMod
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "KnightSnapes"
    Content: >
      👋 Welcome to demo page of Hugo's theme PaperMod!

      - **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.

      - Feel free to show your support by giving us a star 🌟 on GitHub and sharing with your friends and social media .

 
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
